### ISSUE TITLE
Need explanation | Idea !

### ISSUE THREAD

**Issue by youssefabc** [Orange-OpenSource/Orange-Boosted-Angular#11]
Hello;
For which reason you put the folder docs?
i integrated Angular CLI in this tempalte :), and i ask if i can move all folders from Docs to Src in order to respect the structure of cli project and to not complicate matters :)?
Brgds

**Comment by liyokuna** [comment]
Hello @youssefabc,

Can you let me know features that you wanted in my boosted. 
I planned to add angular cli.

**Comment by youssefabc** [comment]
Hello @liyokuna  we have just started the development, so every time we want to add a functionality in our application we rely on boosted. So i think we need all features ;)

although , i think there are no impacts if you add angular cli
