### ISSUE TITLE
o-nav-menu isn't working

### ISSUE THREAD

**Issue by robertIsaac** [Orange-OpenSource/Orange-Boosted-Angular#117]
when i apply o-nav-menu to li it gets hidden

i think because the selector is `lib-li[o-nav-menu]` and not `li[o-nav-menu]`

**Comment by robertIsaac** [comment]
replacing `lib-li[o-nav-menu]` by `li[o-nav-menu]`
everything seems fine but if you actually used it throw the following error
```
ERROR NullInjectorError: StaticInjectorError(AppModule)[NgbDropdownToggle -> NgbDropdown]: 
```
the the whole website is down

**Comment by BehnooshShiva** [comment]
Hello @robertIsaac
How do you use "lib-li[o-nav-menu]" ?
for exemple , It is displayed correctly when I'm doing :
<li o-nav-link route="" title=""><a href="" class="nav-link">Test</a></li>

**Comment by BehnooshShiva** [comment]
Hello @robertIsaac
How do you use "lib-li[o-nav-menu]" ?
for exemple , It is displayed correctly when I'm doing :
`<li o-nav-link route="" title=""><a href="" class="nav-link">Test</a></li>`

**Comment by BehnooshShiva** [comment]
@robertIsaac 
You are right, I will delete the lib in lib-li.
Here is an example for using "o-nav-menu", I will add it in the doc
`    <li ngbDropdown o-nav-menu menuTitle="Toggle dropdown">
        <div ngbDropdownMenu aria-labelledby="dropdownBasic1">
            <button ngbDropdownItem>Action - 1</button>
            <button ngbDropdownItem>Another Action</button>
            <button ngbDropdownItem>Something else is here</button>
        </div>
    </li>`

**Comment by BehnooshShiva** [comment]
pull request #119
