### ISSUE TITLE
Upgrade to Angular 7

### ISSUE THREAD

**Issue by coloneljack** [Orange-OpenSource/Orange-Boosted-Angular#12]
Hello,

Is there an upgrade to Angular v7+ planned ? 

We tried to do this for our application (which depends on ng-boosted), but build fails due to incompatibilities on Angular versions.

Thanks in advance !

**Comment by liyokuna** [comment]
Hello,

Yes ! It's planned.

**Comment by liyokuna** [comment]
Check this https://github.com/Orange-OpenSource/Orange-Boosted-Angular/releases/tag/4.0.0
