### ISSUE TITLE
moving mouse cursor swiper throw error

### ISSUE THREAD

**Issue by robertIsaac** [Orange-OpenSource/Orange-Boosted-Angular#120]
if the mouse cursor moved over the swiper when the page just loaded it will throw this error
```
ERROR TypeError: Cannot read property 'autoplay' of undefined
```
it happens even on https://ng-boosted.orange.com/#/documentation/swiper

![image](https://user-images.githubusercontent.com/14242054/66897785-05381480-eff8-11e9-8d7e-ecf7af7e7679.png)

**Comment by BehnooshShiva** [comment]
@robertIsaac 
Hello
You are right, you are going to create a PR ?

**Comment by BehnooshShiva** [comment]
Hello @robertIsaac 
I just did a PR
I saw your PR but it was not in the right issue.

**Comment by robertIsaac** [comment]
> Hello @robertIsaac
> I just did a PR
> I saw your PR but it was not in the right issue.

what do you mean?
my PL #121 seems exactly as yours PL #123
