### ISSUE TITLE
Issue while upgrading from ng-boosted 2.0.0 to any newer version : npm module issue ?

### ISSUE THREAD

**Issue by dreameddeath** [Orange-OpenSource/Orange-Boosted-Angular#13]
Hi,

In my project, I have a strange issue while upgrading from ng-boosted 2.0.0 to any superior version 2.2.2 ==> 3.3.1.

Is it possible to have some help please ?

## Symptoms

The newest versions seems to have conflicts between ng-boosted and angular.

Here comes the error :
```
>ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-12-07T13:16:07.924Z
Hash: f315cc8bebed7e491264
Time: 16111ms
chunk {main} main.js, main.js.map (main) 1.88 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 667 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 302 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 329 kB [initial] [rendered]

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng-boosted/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

## Possible Cause

It seems to come from the content of the npm module : the structure has changed while releasing the 2.2.2 ==> it doesn't seems to ship only the dist directory but the whole project (src, ...) while before it was only the dist directory content.

### package.json
```
{
  "name": "esoft-okapi",
  "version": "0.9",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "test:cli": "ng test --browser=ChromeHeadless --code-coverage=true --single-run=true",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.1.9",
    "@angular/common": "6.1.9",
    "@angular/compiler": "6.1.9",
    "@angular/core": "6.1.9",
    "@angular/forms": "6.1.9",
    "@angular/http": "6.1.9",
    "@angular/platform-browser": "6.1.9",
    "@angular/platform-browser-dynamic": "6.1.9",
    "@angular/router": "6.1.9",
    "@ng-bootstrap/ng-bootstrap": "3.2.2",
    "@types/lodash": "^4.14.116",
    "boosted": "4.1.3",
    "core-js": "^2.5.7",
    "jquery": "^3.3.1",
    "ng-boosted": "2.0.0",
    "popper.js": "^1.14.4",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.4",
    "@angular/cli": "~6.2.4",
    "@angular/compiler-cli": "6.1.9",
    "@angular/language-service": "6.1.9",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "~2.0.4",
    "@types/node": "~6.0.60",
    "codelyzer": "~4.4.4",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "karma-teamcity-reporter": "^1.1.0",
    "protractor": "^5.4.1",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "tslint-language-service": "~0.9.9",
    "typescript": "~2.9.2"
  }
}
```
### ng boosted npm module content

```
> dir node_modules\ng-boosted
 Le volume dans le lecteur C s’appelle System
 Le numéro de série du volume est 6E70-67A3

 Répertoire de C:\Applications\okapi\node_modules\ng-boosted

07/12/2018  13:53    <REP>          .
07/12/2018  13:53    <REP>          ..
23/05/2018  15:05               814 index.d.ts
23/05/2018  15:05             2 135 index.js
23/05/2018  15:05             2 998 index.js.map
23/05/2018  15:05             3 037 index.metadata.json
23/05/2018  15:05               158 index.ngfactory.d.ts
23/05/2018  15:05             4 966 index.ngfactory.js
23/05/2018  15:05             9 156 index.ngfactory.js.map
23/05/2018  15:05            12 540 index.ngsummary.json
07/12/2018  13:51    <REP>          o-carousel
07/12/2018  13:51    <REP>          o-dropdown
07/12/2018  13:51    <REP>          o-navbar
07/12/2018  13:51    <REP>          o-switch
23/05/2018  15:05               577 package.json
07/12/2018  13:51    <REP>          scroll-top
               9 fichier(s)           36 381 octets
               7 Rép(s)  63 428 259 840 octets libres
```
### build/serve
```
okapi>ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-12-07T12:55:12.182Z
Hash: ec1f9071a3144cc80354
Time: 28802ms
chunk {main} main.js, main.js.map (main) 943 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 434 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 302 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.26 MB [initial] [rendered]
i ｢wdm｣: Compiled successfully
```

### package.json
``
{
  "name": "esoft-okapi",
  "version": "0.9",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "test:cli": "ng test --browser=ChromeHeadless --code-coverage=true --single-run=true",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.1.9",
    "@angular/common": "6.1.9",
    "@angular/compiler": "6.1.9",
    "@angular/core": "6.1.9",
    "@angular/forms": "6.1.9",
    "@angular/http": "6.1.9",
    "@angular/platform-browser": "6.1.9",
    "@angular/platform-browser-dynamic": "6.1.9",
    "@angular/router": "6.1.9",
    "@ng-bootstrap/ng-bootstrap": "3.2.2",
    "@types/lodash": "^4.14.116",
    "boosted": "4.1.3",
    "core-js": "^2.5.7",
    "jquery": "^3.3.1",
    "ng-boosted": "2.2.2",
    "popper.js": "^1.14.4",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.4",
    "@angular/cli": "~6.2.4",
    "@angular/compiler-cli": "6.1.9",
    "@angular/language-service": "6.1.9",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "~2.0.4",
    "@types/node": "~6.0.60",
    "codelyzer": "~4.4.4",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "karma-teamcity-reporter": "^1.1.0",
    "protractor": "^5.4.1",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "tslint-language-service": "~0.9.9",
    "typescript": "~2.9.2"
  }
}
```
### ng_boosted npm module content
```
>dir node_modules\ng-boosted
 Le volume dans le lecteur C s’appelle System
 Le numéro de série du volume est 6E70-67A3

 Répertoire de C:\Applications\okapi\node_modules\ng-boosted

07/12/2018  14:14    <REP>          .
07/12/2018  14:14    <REP>          ..
26/10/1985  09:15               276 .editorconfig
07/12/2018  14:14    <REP>          dist
07/12/2018  14:14    <REP>          docs
26/10/1985  09:15             1 463 karma-shim.js
26/10/1985  09:15             2 361 karma.conf.js
26/10/1985  09:15             1 253 LICENSE
26/10/1985  09:15           148 385 ng-boosted-0.0.1.tgz
07/12/2018  14:14    <REP>          node_modules
26/10/1985  09:15               834 NOTICE.txt
26/10/1985  09:15               601 package-dist.json
26/10/1985  09:15             4 762 package.json
26/10/1985  09:15             1 471 README.md
07/12/2018  14:14    <REP>          src
26/10/1985  09:15               524 tsconfig-dist.json
26/10/1985  09:15               887 tsconfig.json
26/10/1985  09:15             1 452 tslint.json
26/10/1985  09:15             8 492 webpack.config.js
```
### Build / Serve
```
>ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-12-07T13:16:07.924Z
Hash: f315cc8bebed7e491264
Time: 16111ms
chunk {main} main.js, main.js.map (main) 1.88 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 667 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 302 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 329 kB [initial] [rendered]

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ng-boosted/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

i ｢wdm｣: Failed to compile.
```

**Comment by liyokuna** [comment]
Hello, 
set the version of your angualr package to 6.1.0.
If it doesn't work, share the console message.

**Comment by liyokuna** [comment]
zero feed back
@dreameddeath
