### ISSUE TITLE
@angular packages are added as dependencies causing "Cannot redeclare block-scoped variable 'ngDevMode'"

### ISSUE THREAD

**Issue by ibenjelloun** [Orange-OpenSource/Orange-Boosted-Angular#14]
Version 4.0.0 of `@ng-boosted` has packages from the `@angular` scope as dependecies : 

```
"dependencies": {
    "@angular/common": "7.0.0",
    "@angular/compiler": "7.0.0",
    "@angular/compiler-cli": "7.0.0",
    "@angular/core": "7.0.0",
    "@angular/forms": "7.0.0",
    "@angular/http": "7.0.0",
    "@angular/platform-browser": "7.0.0",
    "@angular/platform-browser-dynamic": "7.0.0",
    "@angular/router": "7.0.0",
...
```

This is causing the "Cannot redeclare block-scoped variable 'ngDevMode'" error specified in this issue https://github.com/angular/angular/issues/24165.

**Comment by liyokuna** [comment]
How do you get that error messages.
I created a ng project, install ng-boosted, run it and zero errors or warning

**Comment by ibenjelloun** [comment]
Does the main app have a different angular version than the library ?
I'll try to create a small reproduction repo as soon as possible.

**Comment by liyokuna** [comment]
Ng-boosted, is based on Angular 7.
ok let me know. You can use stackbliz if needed.

**Comment by ibenjelloun** [comment]
I'm closing this issue because I'm not able to reproduce.

**Comment by Lausselloic** [comment]
Thanks for your feedback. Let us know if there's any other issues.
And Happy new year
