### ISSUE TITLE
I18N for OCalendarComponent

### ISSUE THREAD

**Issue by lucimed** [Orange-OpenSource/Orange-Boosted-Angular#149]
Actually, it is possible to internationalize this component with translated weekdays and month names but footer buttons labels are hard coded so we can't change them.

**Comment by BehnooshShiva** [comment]
@lucimed 
Footer buttons, you mean "Today" and "Close" buttons ?

**Comment by lucimed** [comment]
@BehnooshShiva 
Yes, "Today" and "Close" labels are hard coded.
They could be Input params for this component to allow modification.

**Comment by BehnooshShiva** [comment]
@lucimed 
Ok, here is the pull request
https://github.com/Orange-OpenSource/Orange-Boosted-Angular/pull/152

**Comment by BehnooshShiva** [comment]
@lucimed 
here it is, done.
I will deliver in the next version.
