### ISSUE TITLE
AOT NullInjectorError: StaticInjectorError(AppModule)[NgbModal -> NgbModalWindow]

### ISSUE THREAD

**Issue by ibenjelloun** [Orange-OpenSource/Orange-Boosted-Angular#151]
When using a different `@ng-bootstrap/ng-bootstrap` version than the one used by ng-boosted, I face this error in aot mode `ng serve --aot` when importing `ONavMenuModule`.

```
NullInjectorError: StaticInjectorError(AppModule)[NgbModal -> NgbModalWindow]: 
  StaticInjectorError(Platform: core)[NgbModal -> NgbModalWindow]: 
    NullInjectorError: No provider for NgbModalWindow!
```

This cannot be reproduced using the demo application in the same workspace, because it will always use the same `@ng-bootstrap/ng-bootstrap` version.

This is probably related to the fact that `ONavMenuModule` is the only module importing  `NgbModule` .

**Comment by BehnooshShiva** [comment]
@ibenjelloun 
here is the correction
#153
