### ISSUE TITLE
Swiper deep import `import Swiper from 'swiper/dist/js/swiper';`  in o-carousel-container.component.ts

### ISSUE THREAD

**Issue by ibenjelloun** [Orange-OpenSource/Orange-Boosted-Angular#170]
Swiper deep import `import Swiper from 'swiper/dist/js/swiper';` in the carousel component 

[o-carousel-container.component.ts](https://github.com/ibenjelloun/Orange-Boosted-Angular/blob/5a12a5eb288865c85bbf73db8379ac602e990d2f/projects/ng-boosted/src/lib/o-carousel/o-carousel-container/o-carousel-container.component.ts#L20)

Warning after updating to Angular 9 :
```
WARNING in Entry point 'ng-boosted' contains deep imports into '..../node_modules/swiper/dist/js/swiper'.
```

**Comment by BehnooshShiva** [comment]
Swiper was removed, please use new component:
https://ng-boosted.orange.com/#/documentation/carousel
