### ISSUE TITLE
[lib-o-navbar] Les dropdown ne fonctionnent pas correctement sur la navbar

### ISSUE THREAD

**Issue by damiengontier** [Orange-OpenSource/Orange-Boosted-Angular#173]
Et c'est même visible quand on essaie de l'utiliser dans la documentation:
https://ng-boosted.orange.com/#/documentation/o-navbar

Le bouton `toggle dropdown` ne fonctionne pas du tout, et si on arrive à le faire marcher, l'attribut `route` ne fonctionne pas, même en ajoutant o-nav-link sur les items du dropdown.

**Comment by Lausselloic** [comment]
Hello toggle dropdown presented in the documentation work on the first launching of the page but not after browsing multiple pages.
I can reproduce the error, sorry for that, you could include a native dropdown instead of `o-nav-menu`

https://ng-bootstrap.github.io/#/components/dropdown/examples

**Comment by BehnooshShiva** [comment]
Please use new Navbar component.
https://ng-boosted.orange.com/#/documentation/navbar

**Comment by BehnooshShiva** [comment]
Please use new Navbar component.
https://ng-boosted.orange.com/#/documentation/navbar
