### ISSUE TITLE
Project's compilation fails with AOT

### ISSUE THREAD

**Issue by NBouton** [Orange-OpenSource/Orange-Boosted-Angular#22]
When we compile our project for production with AOT compiler, we encounter this error :

    ERROR in ng-boosted\dist\index.js.ts(34,38): Error during template compile of 'ɵ0'
      Function expressions are not supported in decorators
        Consider changing the function expression into an exported function.

**Version :** 
angular: 6.1.10
ng-boosted: 3.3.1

It seems that this syntax is not accept by AOT compiler : 

    `var  NgBoostedModule  =  /** @class */ (function () {`

in ng-boosted\dist\index.js
 
    var  NgBoostedModule  =  /** @class */ (function () {
        function  NgBoostedModule() {}
        NgBoostedModule.decorators  = [
	        { type:  NgModule, args: [{
			        imports: [CommonModule, RouterModule, NgbModule],
			        declarations:  NG_BOOSTED_DECLARATIONS,
			        exports:  NG_BOOSTED_DECLARATIONS
		        },] },
        ];
	    return  NgBoostedModule;
    }());

I found this post, if it could help : 
[aot problem "Function expressions are not supported in decorators](https://github.com/amcdnl/ngrx-actions/issues/23)

**Comment by liyokuna** [comment]
check newly release version :)
