### ISSUE TITLE
o-navbar:  cannot use [queryParams]

### ISSUE THREAD

**Issue by pasmory** [Orange-OpenSource/Orange-Boosted-Angular#24]
Hi,
I have got an issue using o-nav-link
I copy paste the sample on https://ng-boosted.orange.com/#/documentation/o-navbar

you have
```
<li o-nav-link route="/documentation">Getting started</li>
```
I add this line
```
<li o-nav-link route="/catalog" [queryParams]="{id: 'my_id'}" >catalog</li>
```
It is not working ==> console error
<li o-nav-link route="/catalog" [ERROR ->][queryParams]="{id: 'my_id'}" >catalog</li>

if I use a new one instead of previous
```
<li o-nav-link [routerLink]="['/catalog']" [queryParams]="{id: 'my_id'}" >catalog</li>
```
==> the color of the nav-link 'catalog' is 'orange' and not white (hover is not working)

How can I fix this?
Thank you

**Comment by liyokuna** [comment]
update can be seen [here](https://ng-boosted.netlify.com/#/documentation/o-navbar)
