### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by youssefabc** [Orange-OpenSource/Orange-Boosted-Angular#25]
Hello everybody,

I am using angular last version only Angular CLI last version too for compiling.
I integrated the ng-boosted it's works fine with chrome, firefox and edge
:/ and not working with IE11

Best regards

**Comment by Lausselloic** [comment]
Hello,
Did you uncomment the required polyfills in your app/src/polyfill.ts to enable IE11 rendering?

**Comment by youssefabc** [comment]
@Lausselloic 
Yes i follow this link https://angular.io/guide/browser-support

**Comment by liyokuna** [comment]
link to https://github.com/Orange-OpenSource/Orange-Boosted-Angular/issues/27
