### ISSUE TITLE
Make ng-boosted compatible with last version of angular cli (12.2.3)

### ISSUE THREAD

**Issue by Potomac** [Orange-OpenSource/Orange-Boosted-Angular#251]
Hello,

I installed the last version of angular/cli (12.2.3),

then I created a new project, inside I tried to install ng-boosted, but I got an error related to a dependency version mismatch for angular-cli, ng-boosted wants angular/cli 12.1.1, but a more recent version of angular/cli is 12.2.3 : 

```
$ npm install --save ng-boosted

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test2@0.0.0
npm ERR! Found: @angular/common@12.2.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~12.1.1" from ng-boosted@10.0.0
npm ERR! node_modules/ng-boosted
npm ERR!   ng-boosted@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Please update the ng-boosted package, in order to make it compatible with the last version of angular/cli.

Thanks

**Comment by Lausselloic** [comment]
Hello, it's a peer dependency declaration, so you could ignore it, with --legacy-peer-deps

I've create a PR to improve the peer dependencies for the next version, but there's no date for the next version at time
