### ISSUE TITLE
This library don't compile with angular 12 !!!

### ISSUE THREAD

**Issue by QLLX3227** [Orange-OpenSource/Orange-Boosted-Angular#254]
While migrating to angular 12, booosted 5 has some dependency issues with angular! 😟 

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: scorentry@0.9.0
npm ERR! Found: @angular/common@12.2.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^12.2.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~12.1.1" from ng-boosted@10.0.0
npm ERR! node_modules/ng-boosted
npm ERR!   ng-boosted@"^10.0.0" from the root project
```

Therefore boosted v5 is not aligned to up to date angular 12. This is an issue for those who want to upgrade to last angular versions.

**Comment by Lausselloic** [comment]
Hello, yes we know this issue but there's a fallback that could be apply before the next release see https://github.com/Orange-OpenSource/Orange-Boosted-Angular/issues/251
