### ISSUE TITLE
Unable to dismiss modals

### ISSUE THREAD

**Issue by Querdos** [Orange-OpenSource/Orange-Boosted-Angular#258]
Hello,

I'm using Ng Boosted and included the modals.
Working fine, except for one thing: modal dismissal with the cross on the top right:

```html
<button type="button" class="btn-close" data-bs-dismiss="modal"><span class="visually-hidden">Close</span></button>
```

The current workaround is to bind the button to a method with (click) but I wanted to know why it wasn't working.
Missing import ? Missing declaration?

Thanks in advance for your help !

**Comment by Querdos** [comment]
More information on my `angular.json`:
```json
"assets": [
    "src/favicon.ico",
    "src/assets",
    "src/manifest.webmanifest"
],
"styles": [
    "node_modules/boosted/scss/boosted.scss",
    "node_modules/boosted/dist/css/orange-helvetica.min.css",
    "node_modules/ng-boosted/style/ng-boosted.scss",
    "node_modules/ngx-toastr/toastr.css",
    "node_modules/font-awesome/css/font-awesome.css",
    "src/styles.scss"
],
"stylePreprocessorOptions": {
    "includePaths": [
        "src/styles/"
    ]
},
"scripts": [
    "node_modules/@popperjs/core/dist/umd/popper.js",
    "node_modules/boosted/dist/js/boosted.min.js"
],
"vendorChunk": true,
"extractLicenses": false,
"buildOptimizer": false,
"sourceMap": true,
"optimization": false,
"namedChunks": true
...
```

**Comment by Lausselloic** [comment]
Hello,

Yes there's an error in documentation data-bs-* are useless for ng-boosted. as explain in ng-bootstrap documentation you need to use the (click) to close the modal.

Regarding your angular.json file, I think you don't need to import boosted.min.js in scripts as JS is handled by ng-boosted

**Comment by Lausselloic** [comment]
Hello @Querdos I've [update the documentation](https://ng-boosted.orange.com/#/documentation/modal). I'll close this issue, please reopen it if you still have an error
