### ISSUE TITLE
Problem with tooltips right & left

### ISSUE THREAD

**Issue by Querdos** [Orange-OpenSource/Orange-Boosted-Angular#260]
Since the migration to `boosted` 5 and `ng-boosted` 10, tooltips right & left are not positioned correctly.

Example with the documentation:
![image](https://user-images.githubusercontent.com/10584706/134471638-c00ea101-89c7-4fd6-962c-ca7564beecd2.png)

**Comment by Lausselloic** [comment]
hello, sorry for the late reply, but current ng-boosted version doesn't match with boosted v5. It rely on ng-bootstrap that is still on beta to support bootstrap v5 : https://ng-bootstrap.github.io/#/home

**Comment by Lausselloic** [comment]
my bad Ng-boosted is announed compliant with boosted v5 so it's an issue.

**Comment by Lausselloic** [comment]
Hello, I just find that position have been renamed from `left`/`right`to `start`/`end` 

I will update the documentation
