### ISSUE TITLE
swiper inclusion in ng-boosted - generate a dom 7 error in too many project

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Angular#27]
https://github.com/angular/angular/issues/28862

That's not the first feedback about that dom7 error.
@liyokuna we need to create a reproduce test-case, and after that see to remove the inclusion of swiper inside ng-boosted. It need to be a peer-dependency like in the next boosted release.

If a project doesn't use swiper, there's no need to load it in nb-boosted

**Comment by liyokuna** [comment]
PR https://github.com/Orange-OpenSource/Orange-Boosted-Angular/pull/28
Enhancement done, moving swiper to peerdep.
