### ISSUE TITLE
Support for Angular 13

### ISSUE THREAD

**Issue by Smixi** [Orange-OpenSource/Orange-Boosted-Angular#291]
Hi,
It seems that we cannot install this library (and update from 12 to 13) as it has a dependy of  @angular/common@"^12.1.1"

```bash
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: managed-firewall-app@0.0.0
npm ERR! Found: @angular/common@13.2.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.2.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.1.1" from ng-boosted@10.1.0
npm ERR! node_modules/ng-boosted
npm ERR!   ng-boosted@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

Is there a planned release for such support ? 

Angular 12 has some vuln found on its peer dependencies corrected on v13, and Angular v12 support will be over on April.

Regards,

**Comment by Lausselloic** [comment]
Hello we know that and we are working to release a version compliant with Angular 13. By the way you don't really need ng-boosted. You could simply used ng-bootstrap with boosted as ng-bootstrap release an official version that support Angular 13 and Bootstrap/boosted 5
sorry for the late reply I miss your reply :-(
So according to Ng-boostrap official supported versions : 
If you want to use angular 12 you need to stay with boosted 4 :-(
https://ng-bootstrap.github.io/#/getting-started

Compatibility table in ng-bootstrap: https://ng-bootstrap.github.io/#/getting-started

You need to remove ng-boosted dependency : 
npm uninstall ng-boosted 
And then work with boosted and ng-bootstrap
npm i --save boosted@5 @ng-bootstrap/ng-bootstrap@12

**Comment by Smixi** [comment]
Thank you for your support, it was only 20 minutes so it's quite fast ^^'.

We will try to do that then :) !
