### ISSUE TITLE
Update Scroll

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Boosted-Angular#37]
Improving scroll event.
Using host listener

**Comment by liyokuna** [comment]
@Aniort I wondering if you can review accessiblity on the element scrool top.
here is the link to [test](https://deploy-preview-38--ng-boosted.netlify.com/#/documentation/o-scroll-top).

**Comment by Aniort** [comment]
ok no accessibility problem detected!
