### ISSUE TITLE
Documentation 2.0.0 is missing

### ISSUE THREAD

**Issue by Handja** [Orange-OpenSource/Orange-Boosted-Angular#4]
Ng Boosted 2.0.0

Documentation link is mapped to collapse component page.

**Expected behaviour**
Display the components list when i click on documentation link.

**Comment by ygatesoupe** [comment]
Hello,
Not sure to understand well the issue, but from what I see component list was not showing on documentation page in desktop view. That's what I fixed in commit ef96b05701
