### ISSUE TITLE
Adding pause and play button for Carousel

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Boosted-Angular#40]
Adding Pause and Play button for the Carousel.

```

- On Focus, the carousel, should stop cycling.

- On Loosing the focus, the cycle must keep going from where it has been stopped.

- On focus, you can use the left or right arrows to slide the items.

- Pressing on pause, must stop the carousel.

- Pressing on play must restart the carousel.

```
Here is the [link ](https://deploy-preview-47--ng-boosted.netlify.com/#/documentation/carousel)to test or review.

**Comment by liyokuna** [comment]
relating to #42

**Comment by liyokuna** [comment]
Hello @Aniort,

Can you check the update made on carousel, here is the [link](https://deploy-preview-42--ng-boosted.netlify.com/#/documentation/carousel).

**Comment by liyokuna** [comment]
Hello @StreiffBerenice , Check the accessibility of the button, please.
here is the [link](https://deploy-preview-42--ng-boosted.netlify.com/)

**Comment by liyokuna** [comment]
I reported a [bug ](https://github.com/ng-bootstrap/ng-bootstrap/issues/3188#issuecomment-491878265)on the carousel to ng bootstrap team.
When setting on pause and clicking to the navigation arrow, the cycle restart again.

**Comment by StreiffBerenice** [comment]
- On Focus, the carousel, should stop cycling.**0K 20/05/2019**
- On Loosing the focus, the cycle must keep going from where it has been stopped. **0K 20/05/2019**
- On focus, you can use the left or right arrows to slide the items. **0K 20/05/2019**
- Pressing on pause, must stop the carousel.  **0K 20/05/2019**
- Pressing on play must restart the carousel. **0K 20/05/2019**
------
But:
IMPORTANT POINTS
-Circles buttons are not tabulable wirh the keyboard (tab for exemple)
- The focus isn't very visible but more or less valide refering to the wcag 2.1 -> use a black, thick and continuous line. That's true for all focusable elements (btn, links) . Color: black except for the btn "pause" -> the the red-orange of Orange's Chart
-Proximity between the "pause" button" and the carousel. People who are zooming a lot can not see the button. The bt pause and the circles links should be very close to the carousel, below and to the left side.
- Optionnal: the "circles buttons" should be bigger
- For semantical reasons, I would prefer reals buttons for arrows and circles. For senior and people who have a mental disability, I woudl like to add a title attribute which has teh same content as the aria-label attribute. Example : <button _ngcontent-c5="" class="btn btn-outline-dark btn-sm icon-Pause" id="changeState" type="button" ng-reflect-klass="btn btn-outline-dark btn-sm" ng-reflect-ng-class="icon-Pause" aria-label="set Pause"></button>
