### ISSUE TITLE
Navbar Dropdown 2.0.0 menu is broken

### ISSUE THREAD

**Issue by Handja** [Orange-OpenSource/Orange-Boosted-Angular#5]
In the navbar, when I click on the dropdown button (o-nav-menu), dropdown menu is displayed, but when I click outside of this menu to make it collapse, nothing happens and a JS error occurs :

`Cannot read property 'anchorEl' of undefined`
`Cannot read property 'isEventFrom' of undefined`

This behaviour also appears in your documentation site : http://ng-boosted.orange.com/#/documentation/o-navbar

**Comment by ygatesoupe** [comment]
Looks like there is an issue between NgDropdown and o-nav-menu in navbar. Apparently ngbDropdown needs ngbDropdownToggle at the time of creation. 

https://github.com/ng-bootstrap/ng-bootstrap/issues/2343

For now I would recommend not to use o-nav-menu component but native NgDropdown like this in navbar :

```html
<li ngbDropdown class="nav-item dropdown">
  <a class="nav-link" id="dropdownBasic1" ngbDropdownToggle>Contribute</a>
  <div ngbDropdownMenu aria-labelledby="dropdownBasic1">
    <a class="dropdown-item" href="#">Github</a>
    <a class="dropdown-item" href="#">About Markdown</a>
  </div>
</li>

**Comment by shawnrmoss** [comment]
Running into the issue. 

We had *ngIf="condition" on our ngbDropdownToggle elements.

When we updated to v1.1.2 because of an angular update we couldnt just revert to an earlier version.  We kept getting the error. 

Replace the *ngIf with something like:
[style.display]="condition ? 'inline': 'none'"

This worked for use.

**Comment by pkozlowski-opensource** [comment]
@ygatesoupe @Handja yep, you must use one of the `NgbDropdownToggle` or `NgbDropdownAnchor` directives inside an element marked with `ngbDropdown`. This is needed so we know where to position a dropdown menu window: https://ng-bootstrap.github.io/#/components/dropdown/api. Without this anchoring element we wouldn't be able to position dropdown's menu.

**Comment by liyokuna** [comment]
hello @pkozlowski-opensource 
I want to know if there is a change made into ngbDropdown ?
Actually, I  released a version of our fremawork. We have a custom dropdown  that uses `ngbDropdwon`. But when i include my package inside an angular project, I am running to this error messages:
```
ERROR Error: StaticInjectorError(AppModule)[ODropdownComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[ODropdownComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
```
The code didn't change. Here is the [link to component](https://github.com/Orange-OpenSource/Orange-Boosted-Angular/blob/master/src/o-dropdown/o-dropdown.component.ts).

**Comment by yvernet** [comment]
Hello @liyokuna 

I still face this issue when using ngbDropdown

```
ERROR Error: StaticInjectorError(AppModule)[ODropdownComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[ODropdownComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
```

Any fix to this ?

**Comment by liyokuna** [comment]
@yvernet 
Can you tell me how you set up your environment so as to reproduce that.
Paste your angular version, ng-boosted version,...

**Comment by yvernet** [comment]
I just made a migration from Angular 5 to Angular 7 and I had this error. To try to figure out the problem, I replaced my own drop down menu by the one given in example in the documentation:

```
<div ngbDropdown class="d-inline-block">
    <button class="btn btn-info" id="dropdownMenu1" ngbDropdownToggle>Toggle dropdown</button>
    <div ngbDropdownMenu aria-labelledby="dropdownMenu1">
        <a class="dropdown-item" href="#">Action 1</a>
        <a class="dropdown-item" href="#">Another Action</a>
        <a class="dropdown-item" href="#">Something else is here</a>
    </div>
</div>
```

But I still have the error.

**Versions**
angular: 7.0.0
boosted: 4.1.3
ng-boosted: 4.0.0
