### ISSUE TITLE
Swiper Pause and play

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Boosted-Angular#50]
The swiper need to have a button for pause and play.
Must be similar to #40 .
Update:

```

- On Focus, the carousel, should stop cycling.

- On Loosing the focus, the cycle must keep going from where it has been stopped.

- On focus, you can use the left or right arrows to slide the items.

- Pressing on pause, must stop the carousel.

- Pressing on play must restart the carousel.

```
Here is the [link ](https://deploy-preview-47--ng-boosted.netlify.com/#/documentation/swiper)to test or review.

**Comment by liyokuna** [comment]
Setting on pause and clicking on one of the arrows navigation make the cycle restart.

**Comment by StreiffBerenice** [comment]
see my commentary on "carousel" component.
