### ISSUE TITLE
Angular Elements Instead Of Package

### ISSUE THREAD

**Issue by aakashgarg19** [Orange-OpenSource/Orange-Boosted-Angular#54]
Hi Boosted Team,
    Just an idea, can the team publish all the components in form of Angular Elements instead of this package. As Angular Elements can be used in any project irrespective of framework.

Will like to hear back from your side on this.

**Comment by liyokuna** [comment]
Hello @aakashgarg19 ,

Angular Elements are custom component defining a new [html elements](https://angular.io/guide/elements). It make me think of Web Component.
I understand that and actually you can use that without regard to framework.
We didn't plan to do so. But it worth dig it.
@Lausselloic

**Comment by aakashgarg19** [comment]
Hello @liyokuna thanks for considering the suggestion. If we can have such setup, it will also help application owners to upgrade their application more successfully. So that they can use Angular elements for new development and can migrate existing code time to time. Just a thought though. Maybe not in this package, maybe a separate package can be created.

**Comment by liyokuna** [comment]
Hello,

I share [here ](https://blog.angularindepth.com/how-to-compile-your-angular-components-library-into-web-components-47ff0ac73bd7)an articles that can help.
