### ISSUE TITLE
Upgrade to Angular 6

### ISSUE THREAD

**Issue by coloneljack** [Orange-OpenSource/Orange-Boosted-Angular#6]
Hello,

Do you have an upgrade planned to Angular 6 ? 

Indeed, your last version (2.0.0) is compatible with ng-bootstrap 2.0.0 and Angular 5.2.9, but ng-bootstrap needs Angular 6 (and RxJS 6). Is there no risk of uncompatibilities (mostly with changes of imports in RxJS) ?

**Comment by liyokuna** [comment]
Hello,

Yes we did that
check this [version](https://github.com/Orange-OpenSource/Orange-Boosted-Angular/releases/tag/v2.2.2)
