### ISSUE TITLE
Pagination - Char ">>" appears inside next/previous button

### ISSUE THREAD

**Issue by Handja** [Orange-OpenSource/Orange-Boosted-Angular#7]
When i click on next or previous button, it's focused and the char **>>** appears inside the button.

Example here
http://ng-boosted.orange.com/#/documentation/pagination

**Comment by Zahma** [comment]
@Handja did you find a solution to this issue ?

**Comment by liyokuna** [comment]
it is Related to Boosted.
@Lausselloic 
to correct asap.

**Comment by Handja** [comment]
> @Handja did you find a solution to this issue ?

Not for this moment

**Comment by Handja** [comment]
I've add a temporary fix for this.

```
.page-link span {
display: none;
}
```

**Comment by liyokuna** [comment]
Hello,
to fix this a [change ](https://github.com/ng-bootstrap/ng-bootstrap/pull/2971)have to be made by ng-bootstrap team :)
instead you can use @Handja temp fix

**Comment by liyokuna** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/pull/2971

**Comment by liyokuna** [comment]
Many [options](https://ng-bootstrap.github.io/#/components/pagination/overview#customization) available to resolve this after ng-bootstrap released [V 4.1.0](https://github.com/ng-bootstrap/ng-bootstrap/commit/da53e3dbeb55d22d31832d58ff34bf9a5716f038).
I did this for our [case](https://deploy-preview-58--ng-boosted.netlify.com/#/documentation/pagination).

**Comment by liyokuna** [comment]
#58
