### ISSUE TITLE
OCarousel : problem when building with AOT

### ISSUE THREAD

**Issue by yakari** [Orange-OpenSource/Orange-Boosted-Angular#71]
Hello,

With the latest Ng-Boosted version (4.1.3), the build fails when in AOT mode, because the property 'pause' is defined as private in o-carousel-container.component.ts, but it is referenced in its html template:

```
[INFO] ERROR in node_modules/ng-boosted/o-carousel/o-carousel-container.component.d.ts.OCarouselContainerComponent.html(9,111): : Property 'pause' is private and only accessible within class 'OCarouselContainerComponent'.
[INFO] node_modules/ng-boosted/o-carousel/o-carousel-container.component.d.ts.OCarouselContainerComponent.html(9,164): : Property 'pause' is private and only accessible within class 'OCarouselContainerComponent'.
```

**Comment by yakari** [comment]
https://github.com/Orange-OpenSource/Orange-Boosted-Angular/pull/72

**Comment by Lausselloic** [comment]
thanks I will merge it

**Comment by liyokuna** [comment]
@yakari This [version ](https://github.com/Orange-OpenSource/Orange-Boosted-Angular/releases/tag/4.1.4-beta.1)is a fix that have the correction.
