### ISSUE TITLE
Is this package compatible with Angular 8?

### ISSUE THREAD

**Issue by aakashgarg19** [Orange-OpenSource/Orange-Boosted-Angular#73]
Having a new project requirement and thinking of making it with Angular 8. Can you give any insights whether this package will be compatible with Angular 8 or not?

**Comment by liyokuna** [comment]
The current package is not compatible witn Angular 8.
the next will be.

**Comment by liyokuna** [comment]
#87

**Comment by liyokuna** [comment]
Check this [release](https://github.com/Orange-OpenSource/Orange-Boosted-Angular/releases/tag/5.0.0.beta-0).
