### ISSUE TITLE
o-switch - is there a way to set the input name?

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Angular#8]
https://github.com/Orange-OpenSource/Orange-Boosted-Angular/blob/52333dfcb338e2362bf6b17e260563513cc1ad66/src/o-switch/o-switch.component.ts#L17

Looks like there's no param to define the component name, which usefull when using it in a form component.

Is there a way to add a param to define the name?

**Comment by liyokuna** [comment]
yes !
I can add a name attribute at this html tag.
name="input ID"

**Comment by Lausselloic** [comment]
thanks, it's a good first step, but input name is not always the same as input ID, maybe it will be better to add an input param to the component different from the inputId?
Maybe @Aniort or @sdeschamps-orange or @PigeardSylvain or @ygatesoupe have an idea?
